name: Build Complete Multi-Format Site with Pandoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Pandoc and LaTeX
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic

    - name: Prepare output folder
      run: |
        mkdir -p output/assets
        cp assets/style.css output/assets/
        cp assets/header.html output/assets/
        cp assets/footer.html output/assets/
        if [ -f assets/cover.jpg ]; then cp assets/cover.jpg output/assets/; fi

    - name: Generate PDF
      run: |
        pandoc src/*.md \
          --metadata-file=metadata.yaml \
          --pdf-engine=xelatex \
          --toc \
          --include-before-body=assets/cover.tex \
          -o output/document.pdf

    - name: Generate EPUB
      run: |
        pandoc src/*.md \
          --metadata-file=metadata.yaml \
          --toc \
          --epub-cover-image=assets/cover.jpg \
          -o output/document.epub

    - name: Generate HTML Pages
      run: |
        for file in src/*.md; do
          name=$(basename "$file" .md)
          case "$name" in
            index) outname="index.html" ;;
            01-intro) outname="intro.html" ;;
            02-chapter1) outname="chapter1.html" ;;
            *) outname="${name}.html" ;;
          esac

          pandoc "$file" \
            -s \
            --toc \
            --css=assets/style.css \
            --include-before-body=output/assets/header.html \
            --include-after-body=output/assets/footer.html \
            -o output/"$outname"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site-outputs
        path: output/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
